name: just_dm_ui
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.3
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  url_launcher: ^6.3.0
  go_router: ^14.2.1
  jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.6
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/Poppins-BoldItalic.ttf
  #         weight: 700
  #         style: italic
  uses-material-design: true
